### PR TITLE
chef versions >= 12.14

### PR DESCRIPTION
**Pull request by secmff**
This cookbook failed with chef version 12.14 and higher. This PR fixes that and issue 34.
I've added some unit tests as well and successfully ran against chef 11, 12.13 and 12.16.

### CODE REVIEW

**Comment by svanharmelen** [comment]
Hi @nvwls! How are thing going? Long time no see :wink:

If you have a few minutes, it would be great if you can check this PR as we are still happy users of this cookbook, but of course also want to keep using the latest Chef-Clients.

Thanks!

**Comment by secmff** [comment]
Added requested changes. Thanks!

**Comment by svanharmelen** [comment]
Thanks @nvwls!

**Comment by secmff** [comment]
Thank you.

We would like to start using this version, but that would be a lot easier if you can create a new release and push that to the supermarket, please.

Thanks, Mathijs

**Pull request merged**
