### PR TITLE
Add support for the opscode firewall cookbook

### PR DESCRIPTION
**Pull request by rdoorn**
This will clean up iptables or firewalld rules which are not created using the opscode firewall cookbook.

### CODE REVIEW

**Comment by rdoorn** [comment]
Hello, would you mind merging this request, or let me know why its not merged? Thanks.

**Comment by nvwls** [comment]
Include a minor version bump, updated README and CHANGELOG and I'll merge it.

**Comment by rdoorn** [comment]
Hello, 

README + CHANGELOG updated, also gave it a minor version bump.

Kind Regards,
Ronald

**Comment by rdoorn** [comment]
Thanks! would you be so kind as to also release it to the supermarket.chef.io? then its a set release and makes berkshelf/chef-guard happy out of the box

**Comment by nvwls** [comment]
done

**Comment by rdoorn** [comment]
Awesome!, Thanks!

**Pull request merged**
